id: http://farsightsecurity.com/axamd-client-config-schema#
$schema: http://json-schema.org/draft-04/schema#
title: axamd client configuration
description: configuration for the axamd client
type: object
properties:
        server:
                description: URI to AXAMD server
                type: string
                format: uri
                minLength: 1
        apikey:
                description: Key for authentication
                type: string
                minLength: 1
        timeout:
                description: Socket timeout in seconds
                type: number
                minimum: 0
                exclusiveMinimum: true
        retries:
                description: Number of times to retry failed connections
                type: integer
                minimum: 0
        retry-backoff:
                description: Wait a little longer before each retry attempt (factional seconds)
                type: number
                minimum: 0.3
        sample-rate:
                description: Channel sampling rate (percent)
                type: number
                minimum: 0
                exclusiveMinimum: true
                maximum: 100
        rate-limit:
                description: Maximum packets per second
                type: integer 
                minimum: 0
                exclusiveMinimum: true
        report-interval:
                description: Seconds between server statistics messages
                type: integer
                minimum: 0
                exclusiveMinimum: true
        proxy:
                description: HTTP proxy server
                type: string
                format: uri
                minLength: 1
